### ISSUE TITLE
npm run production

### ISSUE THREAD

**Issue by ashrafalzyoud** [eXolnet/redmine_wbs#60]
```
redmine@redmine:~/redmine-5.1/plugins/redmine_wbs$ npm run production

> production
> mix --production

[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/home/redmine/redmine-5.1/plugins/redmine_wbs/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/redmine/redmine-5.1/plugins/redmine_wbs/node_modules/vue-loader/dist/index.js:29:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Comment by chinatochen** [comment]
The same problem occurs
![Image](https://github.com/user-attachments/assets/2112f820-427e-49d9-bbe3-4706b661c414)
